version: "3.8"

services:

  db:
    image: postgres:15
    container_name: ads-db
    restart: always
    environment:
      POSTGRES_DB: ads
      POSTGRES_USER: ads_user
      POSTGRES_PASSWORD: ads_password
    ports:
      - "5432:5432"
    volumes:
      - ads-db-data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: ads-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USERNAME: ads_user
      DB_PASSWORD: ads_password
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ads

volumes:
  ads-db-data: