spring.application.name=ads

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ads}
spring.datasource.username=${DB_USERNAME:ads_user}
spring.datasource.password=${DB_PASSWORD:ads_password}
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

file.upload-dir=images
